### ISSUE TITLE
Configurar HTTPS

### ISSUE THREAD

**Issue by thicolares** [linguagil/linguagil.github.io#36]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by RodolfoSilva** [comment]
@colares, Tentei fazer isso hoje de manhã mas não tá funcionando, porque precisamos atualizar o servidor DNS que tá apontando para o antigo IP.

Tem que atualizar para esses aqui:

- 185.199.108.153
- 185.199.109.153
- 185.199.110.153
- 185.199.111.153
https://help.github.com/articles/troubleshooting-custom-domains/#dns-configuration-errors
![image](https://user-images.githubusercontent.com/1703020/39573889-70ac8c72-4eab-11e8-9b66-5a0e358e2cad.png)

**Comment by apsferreira** [comment]
@RodolfoSilva atualmente estamos utilizando o servidor dns do Registro.br e redirecionamos para o gh-pages. 

Devo atualizar os servidores para esses ips que você passou no post?
modifico alguma coisa de zona também?

**Comment by RodolfoSilva** [comment]
É só modificar a zona mesmo @apsferreira. Fiz isso, estou aguardando a propagação. Mais tarde eu finalizo essa Issue :stuck_out_tongue:

**Comment by RodolfoSilva** [comment]
https://linguagil.com.br - @colares @apsferreira HTTPS já tá funcionando :smile:

**Comment by RodolfoSilva** [comment]
O https agora tá como padrão.
