### ISSUE TITLE
Definir que todas as seções ocupem toda a altura da tela

### ISSUE THREAD

**Issue by RodolfoSilva** [linguagil/linguagil.github.io#39]
Hoje somente a apresentação do site ocupa 100% da altura da dela.
Acredito que fique melhor se fizermos isso para as outras seções.

**Comment by thicolares** [comment]
Mas acho que os tamanhos mudam muito também. Não sei se seria necessário. Mas o início ficou bem legal mesmo

**Comment by apsferreira** [comment]
não concordo em ocupar 100% a altura da tela para todas as seções, temos muitas variações no conteúdo de cada seção e isso dificulta um pouco mais.
